### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by 32bitx64bit** [Kaiddd/l8xcw#1]
pedophile shit, pretty sure everyone agrees is bad.
Being anti furry while being a furry, pretty ill-redeemable. Pick a side and don't be a hypocrite.
Racism? Sometimes ok, if telling a joke or somethin *as everyones racist towards eachother*. But one of the images was a dude getting his head blown off while the n-word was on screen, thats beyond joking and is just like wtf. 

But political beliefs? no one cares about.
you dont hear people complaining about socialists who have killed way more people then nazi's will ever, so why even bother.

Like im not saying what he did was right, but its really hypocritical to only call out neo-nazi's while socialists and Marxists are very active within the same community seems like a bias.

Also lol no one cares about denying the vax, covid was bs anyways. its the flu just slightly worse now. get over it.

Overall, l8x seems like a pretty terrible person. Though attacking him based on his beliefs Isn't ok, and should never be ok. No matter the situation.

**Comment by Kaiddd** [comment]
His beliefs on vax and stuff just further support what kind of person he is

Also, being a neo nazi is not okay? There being worse groups than neo nazis doesn't make it okay. Hating someone for being a jew, especially when you can be born a jew, is the same thing as hating someone for being black

**Comment by 32bitx64bit** [comment]
> His beliefs on vax and stuff just further support what kind of person he is
> 
> Also, being a neo nazi is not okay? There being worse groups than neo nazis doesn't make it okay. Hating someone for being a jew, especially when you can be born a jew, is the same thing as hating someone for being black

Pussy closed the issue.

*and no, hating jews it not ok. But invalidating what I said also isn't the brightest thing you've ever done.*

**Comment by Kaiddd** [comment]
> > His beliefs on vax and stuff just further support what kind of person he is
> > 
> > Also, being a neo nazi is not okay? There being worse groups than neo nazis doesn't make it okay. Hating someone for being a jew, especially when you can be born a jew, is the same thing as hating someone for being black
> 
> Pussy closed the issue.
> 
> *and no, hating jews it not ok. But invalidating what I said also isn't the brightest thing you've ever done.*
> 
> 

I closed the issue as not planned because there's not really an issue, or needed changes for the cw. If there's any issues with the cw that I believe needed to be changed, I'd do so, but I'm also allowed to close the issue when I don't see any needed changes, I'm not invalidating you.

**Comment by Kaiddd** [comment]
> > His beliefs on vax and stuff just further support what kind of person he is
> > 
> > Also, being a neo nazi is not okay? There being worse groups than neo nazis doesn't make it okay. Hating someone for being a jew, especially when you can be born a jew, is the same thing as hating someone for being black
> 
> Pussy closed the issue.
> 
> *and no, hating jews it not ok. But invalidating what I said also isn't the brightest thing you've ever done.*
> 
> 

You're free to interpret being a neo nazi as not that bad or not needed in the cw, however I'm also free to share that he is a neo nazi

**Comment by 32bitx64bit** [comment]
> > > His beliefs on vax and stuff just further support what kind of person he is
> > > Also, being a neo nazi is not okay? There being worse groups than neo nazis doesn't make it okay. Hating someone for being a jew, especially when you can be born a jew, is the same thing as hating someone for being black
> > 
> > 
> > Pussy closed the issue.
> > _and no, hating jews it not ok. But invalidating what I said also isn't the brightest thing you've ever done._
> 
> You're free to interpret being a neo nazi as not that bad or not needed in the cw, however I'm also free to share that he is a neo nazi

Quite the opposite, being a neo-nazi is a pretty abhorrent thing to be, this is coming from someone who IS a conservative.
Though I don't believe 2 images of him really prove he is, which we're also just out of context, could be trolling for all I know. Wouldn't know sense out of context! 

Seems to be a pretty common theme in this, the more I look through this the more I just see everything out of context or is without context.

**Comment by Kaiddd** [comment]
> > > > His beliefs on vax and stuff just further support what kind of person he is
> > > > Also, being a neo nazi is not okay? There being worse groups than neo nazis doesn't make it okay. Hating someone for being a jew, especially when you can be born a jew, is the same thing as hating someone for being black
> > > 
> > > 
> > > Pussy closed the issue.
> > > _and no, hating jews it not ok. But invalidating what I said also isn't the brightest thing you've ever done._
> > 
> > You're free to interpret being a neo nazi as not that bad or not needed in the cw, however I'm also free to share that he is a neo nazi
> 
> Quite the opposite, being a neo-nazi is a pretty abhorrent thing to be, this is coming from someone who IS a conservative.
> Though I don't believe 2 images of him really prove he is, which we're also just out of context, could be trolling for all I know. Wouldn't know sense out of context! 
> 
> Seems to be a pretty common theme in this, the more I look through this the more I just see everything out of context or is without context. 
> 
> Also just a fyi, the channel where all the nsfw was posted is a 18+ channel, its a childs fault if they whiling ignore it and get exposed to porn, maybe not the best look for a server full of minors to have a channel like that, but its still fully their fault if they decide to ignore all warnings.
> 
> Also no, im not defending this dude dating you, that was wrong. You where a minor and he was a adult, he should've known better.

![Screenshot_20230612-132405_Discord.jpg](https://github.com/Kaiddd/l8xcw/assets/37759450/9108bd73-623f-419b-9158-c74b59ca92c0)

![Screenshot_20230612-132711_Discord.jpg](https://github.com/Kaiddd/l8xcw/assets/37759450/0881e696-b4f2-42b8-a377-15d312054a7d)

Idk what context makes this okay to say to a 16 at the time yr old

Also expo was the one he dated, who is even younger

**Comment by Kaiddd** [comment]
![Screenshot_20230612-173458_Discord.jpg](https://github.com/Kaiddd/l8xcw/assets/37759450/a73df32c-b02a-48f2-b07a-49857a7333d6)

**Comment by Kaiddd** [comment]
Oh and on the basis of trust me (this is possible with all of the other context about this person), he is a huge neonazi, he sends stuff, with seriousness, all the time in many deleted dms, that very clearly show that

**Comment by Kaiddd** [comment]
If you'd like to talk further or need any other screenshots feel free to message me on discord @kaed.e
